[package]
name = "kvstore-inmemory"
version = "0.1.0"
authors = ["Constantine Solovev <constantine.solovev@gmail.com>"]
edition = "2018"

[dependencies]

kvstore-api = { path = "../api" }

thiserror = "1.0"

[dev-dependencies]

tokio = { version ="1.0", features = ["full"] }